<?php

namespace AppBundle\Repository;

/**
 * CleanerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CleanerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($user) {
        return $this->_em->getRepository("AppBundle:Cleaner")->createQueryBuilder('c')
            ->where("user.id = :user")
            ->join("c.user", "user")
            ->setParameter("user", $user->getId())
            ->setMaxResults(1)
            ->getQuery()
            ->getResult()[0];
    }
}
