<?php

namespace AppBundle\Repository;

/**
 * CleanerPlanningDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CleanerPlanningDayRepository extends \Doctrine\ORM\EntityRepository
{
}
