<?php

namespace AppBundle\Repository;

/**
 * CleanerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CleanerRepository extends \Doctrine\ORM\EntityRepository
{
}
