<?php

namespace AppBundle\Repository;

/**
 * GeoCoordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoCoordsRepository extends \Doctrine\ORM\EntityRepository
{
}
