<?php

namespace AppBundle\Repository;

/**
 * OperationTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
