<?php

namespace AppBundle\Repository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name) {
        $name = '%' . $name . '%';
        return $this->_em->getRepository("AppBundle:Operation")->createQueryBuilder('o')
            ->where('place.name LIKE :name')
            ->join("o.place", "place")
            ->setParameter('name', $name)
            ->getQuery()
            ->getResult();
    }

    public function getOperationsByCustomerAndTemplate($customerId, $templateId)
    {
        return $this->_em->getRepository("AppBundle:Operation")->createQueryBuilder('o')
            ->where('customer.id LIKE :customer')
            ->andWhere('template.id LIKE :template')
            ->join("o.place", "place")
            ->join("place.customer", "customer")
            ->join("o.template", "template")
            ->setParameter('template', $templateId)
            ->setParameter('customer', $customerId)
            ->getQuery()
            ->getResult();
    }

    public function getOperationsByCustomer($customerId)
    {
        return $this->_em->getRepository("AppBundle:Operation")->createQueryBuilder('o')
            ->where('customer.id LIKE :customer')
            ->join("o.place", "place")
            ->join("place.customer", "customer")
            ->setParameter('customer', $customerId)
            ->getQuery()
            ->getResult();
    }

    public function getOperationsByTemplate($templateId)
    {
        return $this->_em->getRepository("AppBundle:Operation")->createQueryBuilder('o')
            ->where('template.id LIKE :template')
            ->join("o.template", "template")
            ->setParameter('template', $templateId)
            ->getQuery()
            ->getResult();
    }

    public function getOperationsByGroup($day, $customer, $cleaner)
    {
        return $this->_em->getRepository("AppBundle:Operation")->createQueryBuilder('o')
            ->where('customer.id LIKE :customer')
            ->andWhere("o.day LIKE :day")
            ->andWhere("cleaner.id = :cleaner")
            ->join("o.cleaner", "cleaner")
            ->join("o.place", "place")
            ->join("place.customer", "customer")
            ->setParameter('customer', $customer)
            ->setParameter("cleaner", $cleaner)
            ->setParameter("day", $day)
            ->getQuery()
            ->getResult();
    }

    public function findOperationsByCleaner($cleaner)
    {
        return $this->_em->getRepository("AppBundle:Operation")->createQueryBuilder('o')
            ->where("cleaner.id = :cleaner")
            ->join("o.cleaner", "cleaner")
            ->setParameter("cleaner", $cleaner->getId())
            ->getQuery()
            ->getResult();
    }
}
