<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cleaner;

/**
 * OperationHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOperationHistoriesBetweenTwoDates($date1, $date2)
    {
        return $this->_em->getRepository("AppBundle:OperationHistory")->createQueryBuilder('ohre')
            ->where('ohre.initialDate BETWEEN :date1 AND :date2')
            ->setParameter('date1', $date1->format("Y-m-d 00:00:00"))
            ->setParameter('date2', $date2->format("Y-m-d 23:59:59"))
            ->getQuery()
            ->getResult();
    }
    public function findOperationHistoriesBetweenTwoBeginningDates($date1, $date2)
    {
        return $this->_em->getRepository("AppBundle:OperationHistory")->createQueryBuilder('ohre')
            ->where('ohre.beginningDate BETWEEN :date1 AND :date2')
            ->setParameter('date1', $date1->format("Y-m-d 00:00:00"))
            ->setParameter('date2', $date2->format("Y-m-d 23:59:59"))
            ->getQuery()
            ->getResult();
    }

    public function findOperationHistoriesByCustomerName($customerName)
    {
        return $this->_em->getRepository("AppBundle:OperationHistory")->createQueryBuilder('ohre')
            ->where('ohre.customer LIKE :customer')
            ->setParameter('customer', $customerName)
            ->getQuery()
            ->getResult();
    }

    public function findOperationHistoriesByCustomerNameAndBetweenTwoDates($customerName, $date1, $date2)
    {
        return $this->_em->getRepository("AppBundle:OperationHistory")->createQueryBuilder('ohre')
            ->where('ohre.customer LIKE :customer')
            ->andWhere('ohre.initialDate BETWEEN :date1 AND :date2')
            ->setParameter('date1', $date1->format("Y-m-d 00:00:00"))
            ->setParameter('date2', $date2->format("Y-m-d 23:59:59"))
            ->setParameter('customer', $customerName)
            ->getQuery()
            ->getResult();
    }

    public function findOperationHistoriesByCustomerNameAndBetweenTwoBeginningDates($customerName, $date1, $date2)
    {
        return $this->_em->getRepository("AppBundle:OperationHistory")->createQueryBuilder('ohre')
            ->where('ohre.customer LIKE :customer')
            ->andWhere('ohre.beginningDate BETWEEN :date1 AND :date2')
            ->setParameter('date1', $date1->format("Y-m-d 00:00:00"))
            ->setParameter('date2', $date2->format("Y-m-d 23:59:59"))
            ->setParameter('customer', $customerName)
            ->getQuery()
            ->getResult();
    }

    public function findOperationHistoriesByCleanerAndBetweenTwoDates(Cleaner $cleaner, $date1, $date2)
    {
        $date1copied = clone $date1;
        $date2copied = clone $date2;
        return $this->_em->getRepository("AppBundle:OperationHistory")->createQueryBuilder('ohre')
            ->where('cleaner.id = :cleaner')
            ->andWhere('ohre.initialDate BETWEEN :date1 AND :date2')
            ->join('ohre.cleaner', 'cleaner')
            ->setParameter('date1', $date1copied->format("Y-m-d 00:00:00"))
            ->setParameter('date2', $date2copied->format("Y-m-d 23:59:59"))
            ->setParameter('cleaner', $cleaner->getId())
            ->getQuery()
            ->getResult();
    }
}
