<?php

namespace AppBundle\Repository;

/**
 * OperationTaskTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTaskTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
