<?php

namespace AppBundle\Repository;

/**
 * OperationTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
