<?php

namespace AppBundle\Repository;

/**
 * OperationTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTemplateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOperationTemplateByName($name)
    {
        $name = '%' . $name . '%';
        return $this->_em->getRepository("AppBundle:OperationTemplate")->createQueryBuilder('otre')
            ->where('otre.name LIKE :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getResult();
    }
}
