<?php

namespace AppBundle\Repository;

/**
 * OperationTaskHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTaskHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
