<?php

namespace AppBundle\Repository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOperationsByCustomer($customerId)
    {
        return $this->_em->getRepository("AppBundle:Operation")->createQueryBuilder('o')
            ->where('customer.id LIKE :customer')
            ->join("o.place", "place")
            ->join("place.customer", "customer")
            ->setParameter('customer', $customerId)
            ->getQuery()
            ->getResult();
    }
}
