<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPlaceByName($name)
    {
        $name = '%' . $name . '%';
        return $this->_em->getRepository("AppBundle:Place")->createQueryBuilder('p')
            ->where('p.name LIKE :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getResult();
    }
}
