<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cleaner;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersNotCleaners()
    {
        $users = $this->_em->getRepository('AppBundle:User')->findAll();
        $cleaners = $this->_em->getRepository('AppBundle:Cleaner')->findAll();
        $usersCleaners = [];
        foreach ($cleaners as $cleaner)
            array_push($usersCleaners, $cleaner->getUser());
        $result = [];

        /** @var User $user*/
        foreach ($users as $user) {
            $ret = array_search($user, $usersCleaners);
            if ($ret == false) {
                array_push($result, $user);
            }
        }
        return $result;
    }
}
