AppBundle\Entity\Place:
  attributes:
    id:
      groups: ['place', 'operation', 'cleaner']
    name:
      groups: ['place', 'operation', 'cleaner']
    operations:
      groups: ['place']
    geoCoords:
      groups: ['place', 'operation', 'cleaner']
    customer:
      groups: ['place', 'operation', 'cleaner']

AppBundle\Entity\GeoCoords:
  attributes:
    id:
      groups: ['geocoords', 'place', 'operation', 'cleaner']
    lat:
      groups: ['geocoords', 'place', 'operation', 'cleaner']
    lon:
      groups: ['geocoords', 'place', 'operation', 'cleaner']
#
AppBundle\Entity\OperationTemplate:
  attributes:
    id:
      groups: ['place', 'operation', 'cleaner']
    comment:
      groups: ['place', 'operation', 'cleaner']
    name:
      groups: ['place', 'operation', 'cleaner']
    tasks:
      groups: ['place', 'operation', 'cleaner']

AppBundle\Entity\OperationTaskTemplate:
  attributes:
    id:
      groups: ['geocoords', 'place', 'operation', 'cleaner']
    name:
      groups: ['geocoords', 'place', 'operation', 'cleaner']
    comment:
      groups: ['geocoords', 'place', 'operation', 'cleaner']
    imagesForced:
      groups: ['geocoords', 'place', 'operation', 'cleaner']

AppBundle\Entity\Cleaner:
  attributes:
    id:
      groups: ['cleaner', 'place', 'operation']
    history:
      groups: ['cleaner', 'place', 'operation']
    operations:
      groups: ['cleaner', 'place']
    user:
      groups: ['cleaner', 'place', 'operation']

AppBundle\Entity\Operation:
  attributes:
    id:
      groups: ['operation', 'place', 'cleaner']
    place:
      groups: ['operation', 'cleaner']
    day:
      groups: ['operation', 'place', 'cleaner']
    cleaner:
      groups: ['operation', 'place']
    template:
      groups: ['operation', 'place', 'cleaner']

AppBundle\Entity\User:
  attributes:
    id:
      groups: ['user', 'place', 'operation', 'cleaner']
    email:
      groups: ['user', 'place', 'operation', 'cleaner']
    admin:
      groups: ['user', 'place', 'operation', 'cleaner']

AppBundle\Entity\Customer:
  attributes:
    id:
      groups: ['cleaner', 'customer', 'user', 'operation', 'place']
    name:
      groups: ['cleaner', 'customer', 'user', 'operation', 'place']
    email:
      groups: ['cleaner', 'customer', 'user', 'operation', 'place']
    color:
      groups: ['cleaner', 'customer', 'user', 'operation', 'place']