AppBundle\Entity\Place:
  attributes:
    id:
      groups: ['place', 'operation', 'day', 'cleaner']
    name:
      groups: ['place', 'operation', 'day', 'cleaner']
    address:
      groups: ['place', 'operation', 'day', 'cleaner']
    operations:
      groups: ['place', 'day']
    description:
      groups: ['place', 'operation', 'day', 'cleaner']
    geoCoords:
      groups: ['place', 'operation', 'day', 'cleaner']
    customer:
      groups: ['place', 'operation', 'day', 'cleaner']

AppBundle\Entity\GeoCoords:
  attributes:
    id:
      groups: ['geocoords', 'place', 'operation', 'day']
    lat:
      groups: ['geocoords', 'place', 'operation', 'day']
    lon:
      groups: ['geocoords', 'place', 'operation', 'day']

AppBundle\Entity\Cleaner:
  attributes:
    id:
      groups: ['cleaner', 'place', 'operation', 'day']
    history:
      groups: ['cleaner', 'place', 'operation', 'day']
    operations:
      groups: ['cleaner', 'place']
    user:
      groups: ['cleaner', 'place', 'operation', 'day']

AppBundle\Entity\Operation:
  attributes:
    id:
      groups: ['operation', 'place', 'cleaner']
    place:
      groups: ['operation', 'cleaner']
    day:
      groups: ['operation', 'place', 'cleaner']
    cleaner:
      groups: ['operation', 'place']
    template:
      groups: ['operation', 'place', 'cleaner']

AppBundle\Entity\User:
  attributes:
    id:
      groups: ['user', 'place', 'operation', 'cleaner']
    email:
      groups: ['user', 'place', 'operation', 'cleaner']

AppBundle\Entity\Customer:
  attributes:
    id:
      groups: ['cleaner', 'customer', 'user', 'operation', 'place']
    name:
      groups: ['cleaner', 'customer', 'user', 'operation', 'place']
    email:
      groups: ['cleaner', 'customer', 'user', 'operation', 'place']